### ISSUE TITLE
.ino didn't compile on windows IDE version 1.8.1

### ISSUE THREAD

**Issue by jducifuentes** [n-e-y-s/G27_Pedals_and_Shifter#7]
Tried to change include file paths to windows friendly slashes "/" -> "\\" but same result:

Arduino:1.8.13 (Windows 10), Tarjeta:"Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setXAxis(void*)':

G27_Pedals_and_Shifter:184:3: error: 'G27' was not declared in this scope

   G27.setXAxis(input->axis);

   ^~~

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setYAxis(void*)':

G27_Pedals_and_Shifter:189:3: error: 'G27' was not declared in this scope

   G27.setYAxis(input->axis);

   ^~~

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setZAxis(void*)':

G27_Pedals_and_Shifter:194:3: error: 'G27' was not declared in this scope

   G27.setZAxis(input->axis);

   ^~~

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setButtonStates(int*, int)':

G27_Pedals_and_Shifter:290:5: error: 'G27' was not declared in this scope

     G27.setButton(i, LOW);

     ^~~

G27_Pedals_and_Shifter:294:5: error: 'G27' was not declared in this scope

     G27.setButton(gear - 1, HIGH);

     ^~~

G27_Pedals_and_Shifter:298:5: error: 'G27' was not declared in this scope

     G27.setButton(buttonTable[i], buttons[i]);

     ^~~

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setup()':

G27_Pedals_and_Shifter:359:3: error: 'G27' was not declared in this scope

   G27.begin(false);

   ^~~

C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void loop()':

G27_Pedals_and_Shifter:438:3: error: 'G27' was not declared in this scope

   G27.sendState();

   ^~~

exit status 1

'G27' was not declared in this scope

**Comment by jducifuentes** [comment]
> Tried to change include file paths to windows friendly slashes "/" -> "\" but same result:
> 
> Arduino:1.8.13 (Windows 10), Tarjeta:"Arduino Pro or Pro Mini, ATmega328P (5V, 16 MHz)"
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setXAxis(void*)':
> 
> G27_Pedals_and_Shifter:184:3: error: 'G27' was not declared in this scope
> 
> G27.setXAxis(input->axis);
> 
> ^~~
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setYAxis(void*)':
> 
> G27_Pedals_and_Shifter:189:3: error: 'G27' was not declared in this scope
> 
> G27.setYAxis(input->axis);
> 
> ^~~
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setZAxis(void*)':
> 
> G27_Pedals_and_Shifter:194:3: error: 'G27' was not declared in this scope
> 
> G27.setZAxis(input->axis);
> 
> ^~~
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setButtonStates(int*, int)':
> 
> G27_Pedals_and_Shifter:290:5: error: 'G27' was not declared in this scope
> 
> ```
>  G27.setButton(i, LOW);
> 
>  ^~~
> ```
> 
> G27_Pedals_and_Shifter:294:5: error: 'G27' was not declared in this scope
> 
> ```
>  G27.setButton(gear - 1, HIGH);
> 
>  ^~~
> ```
> 
> G27_Pedals_and_Shifter:298:5: error: 'G27' was not declared in this scope
> 
> ```
>  G27.setButton(buttonTable[i], buttons[i]);
> 
>  ^~~
> ```
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void setup()':
> 
> G27_Pedals_and_Shifter:359:3: error: 'G27' was not declared in this scope
> 
> G27.begin(false);
> 
> ^~~
> 
> C:\Users\demo\Desktop\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter-master\G27_Pedals_and_Shifter\G27_Pedals_and_Shifter.ino: In function 'void loop()':
> 
> G27_Pedals_and_Shifter:438:3: error: 'G27' was not declared in this scope
> 
> G27.sendState();
> 
> ^~~
> 
> exit status 1
> 
> 'G27' was not declared in this scope




Edit: Working now......, I was selecting wrong arduino board (must select arduino micro adn compiles ok)

Sorry
